### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by zhengxs2018** [zhengxs2018/ai#6]
## LLM APIs

- [x] [百度文心一言大模型](https://aistudio.baidu.com/cooperate/yiyan) (飞桨平台分发)
  - [x] Chat
  - [x] Embeddings
  - [ ] ~~Images~~ 飞浆平台不支持
- [x] [阿里通义千问大模型](https://tongyi.aliyun.com/)
  - [x] Chat 支持 [通义千问 VL](https://help.aliyun.com/zh/dashscope/developer-reference/qwen-vl-plus) 模型
  - [x] Embeddings
  - [ ] ~~Audio~~ 等 [文档](https://help.aliyun.com/zh/dashscope/developer-reference/sambert-speech-synthesis) 的请求地址补全后再尝试
  - [x] Images
    - [x] generate
- [x] [讯飞星火认知大模型](https://xinghuo.xfyun.cn/)
  - [x] Chat
  - [ ] ~~Embeddings~~ 未获得资格
  - [ ] ~~Images~~ 未获得资格
- [x] [腾讯混元助手大模型](https://hunyuan.tencent.com/)
  - [x] Chat
- [x] [Minimax](https://api.minimax.chat/)
  - [x] Chat
  - [x] Embeddings
  - [x] Audio
    - [x] speech.create
  - [ ] Files
  - [ ] Retrieval（知识库检索）
- [x] [Google Gemini](https://ai.google.dev/tutorials/rest_quickstart) 
  - [x] Chat
  - [ ] Embeddings
- [x] [ImagineArt](https://platform.imagine.art/api-reference)
  - [x] Images
    - [ ] createVariation
    - [x] edit
    - [x] generate
    - [x] upscale
    - [ ] restoration
